### ISSUE TITLE
Oauth2 App database should not require the refresh_endpoint

### ISSUE THREAD

**Issue by forslund** [OpenVoiceOS/selene_api#59]
According to the specs for oauth2 the token endpoint shall be used for the refresh: https://www.oauth.com/oauth2-servers/making-authenticated-requests/refreshing-%20%20an-access-token/

I suggest we deprecate the argument in the [OAuthApplicationDatabase](https://github.com/OpenVoiceOS/ovos-backend-client/blob/dev/ovos_backend_client/database.py#L404), or can it be cut completely without breaking the entire world?

**Comment by JarbasAl** [comment]
i'd say we cut it and bump a version number to signal the breaking change just in case, only the HA plugin, alerts skill and spotify use oauth, not too much out there for us to update

assigned the 3 relevant maintainers to this issue so everyone is in the loop

**Comment by mikejgray** [comment]
@forslund @JarbasAl I just took a look at the HA plugin. I don't think it's event using this as it's delegating to the OAuth plugin entirely, so as long as that plugin can handle it we shouldn't have a problem.

**Comment by forslund** [comment]
Closed via #61
